### ISSUE TITLE
Events page not showing room location/

### ISSUE THREAD

**Issue by scioffi** [rit-sse/events#21]
The Events page should show the location of the event if applicable.

**Comment by kristenmills** [comment]
Oh...yeah. That make sense

**Comment by kristenmills** [comment]
There used to be individual event show pages but I got rid of them because I didn't want to implement them and they were pretty useless...but they did have location so I guess they weren't that useless. 

I don't think we should bring them back...just stick location somewhere in the event component.

**Comment by kristenmills** [comment]
@DanSwtmn Did you fix this. If so resolve pls.

**Comment by DanSwtmn** [comment]
Issue has been fixed

**Comment by kristenmills** [comment]
Sweet deal
