### ISSUE TITLE
Title too long error message

### ISSUE THREAD

**Issue by djrenren** [rit-sse/events#6]
When the title is too long, it should say so instead of "Unprocessable Entity"

**Comment by kristenmills** [comment]
Closed as duplicate of #1

**Comment by djrenren** [comment]
Why not just reference the task from the parent task? Or at least update the other task with a list of required error messages.

Otherwise we could close all tasks as dups of a "Make it good" task.

**Comment by kristenmills** [comment]
Sorry, I should have explained my reasoning for closing this better. 

This is to granular and a symptom of a bigger problem. The actual task I care about is display validation messages instead of "Unprocessable Entity". I don't care on any level what the validation messages are as far as events is concerned. And if I don't care in this context, I don't need an issue for it.
